name: Trigger auto deployment for ca-sm-dev-010

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-sm-dev-010-AutoDeployTrigger-333ef39a-21f1-4f9a-87f5-58bfa817561f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CASMDEV010_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CASMDEV010_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CASMDEV010_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: smdev.azurecr.io
          registryUsername: ${{ secrets.CASMDEV010_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CASMDEV010_REGISTRY_PASSWORD }}
          containerAppName: ca-sm-dev-010
          resourceGroup: funcsche
          imageToBuild: smdev.azurecr.io/ca-sm-dev-010:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


